print(type(2+3))
print(type(2+3))
print(type(6/2))
print("first three done")
print(type(2 != 3))
print(type(5 or 6))
print(type(print))
print("second three done")
print(type(print(2*2)))
print(type("abc".find))
print(type("bubu"*2))
print(type(["abc", 2]))
print(type("abc"[2]))
print(type("abcabcabc".split("a")))
print(type("bubu"*(4/2)))